# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Create release

on: [push]
jobs:
  create-ticket:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create ticket
        run: sh ../release.sh
        env:
          OAuth: ${{ secrets.OAuth }}
          OrganizationId: ${{ secrets.OrganizationId }}
